---
name: GitHub Pages

on:
  push:
    branches: ["dev", "update-dev"]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  Pages:
    uses: dennykorsukewitz/DK4/.github/workflows/reusable.pages.yml@dev
